name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install -r requirements.txt --system
      - name: Build executable
        run: pyinstaller WorldClockHUD.spec

      - name: Setup .NET (for WiX)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Accept WiX OSMF EULA
        run: wix eula accept wix7

      - name: Install WiX UI Extension
        run: wix extension add -g WixToolset.UI.wixext


      - name: Build MSI Installer
        shell: powershell
        run: |

          $version = "${{ github.ref_name }}".TrimStart('v')
          if (-not $version) { $version = "1.0.0" } # Заглушка, если запуск не по тегу

          wix build installer\WorldClockHud.wxs -ext WixToolset.UI.wixext -d Version=$version -o dist\WorldClockHud.msi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/WorldClockHud.exe
            dist/WorldClockHud.msi
          draft: false
          generate_release_notes: true
          append_body: true
          body: |
            ## 📥 Download Instructions
            
            - 🌟 **Recommended (`.msi`)**: Download **`WorldClockHud.msi`** to easily install the app. The installer automatically configures the clock to run silently on Windows startup and adds a convenient Start Menu shortcut!
            - 📦 **Portable (`.exe`)**: Download **`WorldClockHud.exe`** if you prefer a standalone version without installation. Just download and run.
            
            ---

